---
- name: KVM host
  hosts: kvmhost
  sudo: True
  tasks:
  - name: update cache
    apt: update_cache=yes cache_valid_time=3600
  - name: Install kvm
    apt: name=qemu-kvm state=present
  - name: Install libvirt-bin
    apt: name=libvirt-bin state=present
  - name: Install virtinst
    apt: name=virtinst state=present
  - name: Install fail2ban
    apt: name=fail2ban state=present
  roles:
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
